kaminari を使ってページング処理を実装する
pofkuma/fjord-books_app pull request #2
Opened 2021-12-15 11:54 UTC by pofkuma

「kaminari を使ってページング処理を実装する」の提出物です。

ご確認よろしくお願いします。

2021-12-20 14:13 UTC, u1tnk requested changes

2021-12-20 14:13 UTC, u1tnk commented on app/controllers/books_controller.rb
> +    @books = Book.order(:id).page params[:page]
per(1ページごとの件数)も設定するようにしましょう。

2021-12-20 21:32 UTC, pofkuma commented on config/initializers/kaminari_config.rb
> +  config.default_per_page = 1
`rails g kaminari:config` で生成して、ここで1ページごとの件数を設定しました。

2021-12-20 21:34 UTC, pofkuma commented on app/controllers/books_controller.rb
> +    @books = Book.order(:id).page params[:page]
@u1tnk 
https://github.com/pofkuma/fjord-books_app/pull/2/files#r772680909
↑こちらで設定しているのすが、問題ないでしょうか？

2021-12-21 01:42 UTC, u1tnk approved these changes

2021-12-21 01:42 UTC, u1tnk commented on app/controllers/books_controller.rb
> +    @books = Book.order(:id).page params[:page]
`Book.order(:id).page(params[:page]).per(PAGE_PER)`のようにここで設定するのがよく見ます(実アプリでは機能によって件数違ったりもするので)が、設定はできているので問題ありません 👍

2021-12-21 10:38 UTC, pofkuma commented on app/controllers/books_controller.rb
> +    @books = Book.order(:id).page params[:page]
@u1tnk 
> Book.order(:id).page(params[:page]).per(PAGE_PER)のようにここで設定するのがよく見ます(実アプリでは機能によって件数違ったりもするので)

そうなんですね！
覚えておきます、ありがとうございます🙏

2021-12-21 10:38 UTC, merged